name: Apache Benchmark Test

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target URL for load testing"
        required: true
      repeat_times:
        description: "Number of test iterations"
        required: true
        default: "5"

jobs:
  ab-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install ApacheBench (ab)
        run: sudo apt-get update > /dev/null && sudo apt-get install -y apache2 > /dev/null

      - name: Run Apache Benchmark Test
        run: |
          echo "Starting ApacheBench test for target: ${{ github.event.inputs.target }}"
          ab -n 100000 -c 500 "${{ github.event.inputs.target }}"
      - name: Save Test Results
        run: |
          for i in $(seq 1 ${{ github.event.inputs.repeat_times }}); do
            echo "Running iteration $i..."
            ab -n 100000 -c 500 "${{ github.event.inputs.target }}" >> result.txt
            echo "Iteration $i complete."
          done
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ab-results
          path: result.txt
