name: Apache Benchmark Test

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target URL for load testing"
        required: true
      repeat_times:
        description: "Number of test iterations"
        required: true
        default: "5"
  workflow_call:
    inputs:
      target:
        description: "Target URL for load testing"
        required: true
        type: string
      repeat_times:
        description: "Number of test iterations"
        required: true
        default: "5"
        type: string

jobs:
  ab-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Install ApacheBench (ab)
        run: |
          sudo apt-get update && sudo apt-get install -y apache2


      - name: Check IP Address
        run : curl 4.ipw.cn

      - name: Run Apache Benchmark Test
        run: |
          echo "Starting ApacheBench test for target: ${{ github.event.inputs.target }}"
          for i in $(seq 1 ${{ github.event.inputs.repeat_times }}); do
            echo "Running iteration $i..."
            ab -n 100000 -c 500 "${{ github.event.inputs.target }}" || echo "Iteration $i failed, continuing..."
            echo "Iteration $i complete."
          done
        continue-on-error: true
